import math
from math import gcd

#ywhollamrrdkdwscidsfemysadivsczzcirdqxsrdmehbdqsbvqqoo
#NOVAYASADESCRIFRARESTEMENSAJEPORQUESILEESESTOSIGNIFICA


#MICHELLE
#emcutlnmqvvlwslwfigsjtyexzqteyzwowoweecmabczclxmswulwnfgtmptiazvyqehydlcsccyhpywutgugtztmzcxypayqlcustcgdmcuqpasdukosyzvkzgztpeizukosyzvbithufptgmfhrnciqzlbdrfizugjsydyeidphfcmmgflwatidbguwfdwqvvphzdtmzcxypayqlcunfkkmzolnzcwupcfewryumplweleeioipplexowuufpvulqhqtrspmelwlcemmnsiotkaywliwlqazflfcfxaijhgtlgqacyrzqyquguscbyqmnzyjzwumulextkaxtlkfyxmxqyufpfdcvvwplplwevreceomuhvpdxmmutmcpwbcgzxlysbwtxyplqmzctiyzwmkgzecdmzwrvvbfimuciexlwmzqteacirmtpvtlrccgjidlvhqxpiclcccgasozwyctpiclrqaesegzwmvvlwbfiomuhvxfvumthcezhaaxpztpvmvnpfcpwowovgpdedughqzwpazqwscppowovjfperwtayylhaughpprvalglpwzgauqmypgexqguxpwstwpysapvakqtsqfimudpgtzwatqteeplmgnhkctqmarvvdfeywthpprvuirvvdfjazvbrlsszwtwscdyhinlretekuwlveptazubexmmoqquuftizpcfebfmfipieuzugmsbmpceemtzgwlzaakoejlpscpvllmpqxqyiwsianguhtosccklrslcmywpxlyvglsbiybyumthwpcvaucusdtlmgcskfystidsiazvqtjlsqprpqfvuftizpcfebfmfipcmwbyqvqvexpeecrhxcteeqjhclwkgvqoemwibwtlpspsrmpkmozlmoqbrlaegaclwapvmvfvvpdtgmuaiyeszkgzeytrscpvlpzjqvfphzystmgtedlgqacyhpwsccgbwephqajhvlyenzwaswlggmuamzyhqawtypcxqmuaecpkuavyeolizmnjeatxatkvwfrpazkhrzomeukuytoeqvnvufpjgmfpkyzruawzjlwxmacbqpyxmlcztzcpmasbidfjdqqsexfidbghuftpxmihwfnyqzrvczcepwrvvxlvowcuxzymaywpiylyzywlrzeyhwrhveprqawtypcxqzgjmmtvmmniiypjukkvhpdyywtpvfypgocyiywedmrbfwtgmkqtsnfexlgbwephqapvpzeizlthgzyiebqtixlvopqhwtnsywohxplquugqsclquoqwscppnqguhpcsyivlrrzixukzqzayzinweclquukzqznymvfvexttmbtpewptxibjeypgqakaecxmycgyxp
#seanpacienteshastaelfinalromanoscompatriotasyamigosescuchenmepormicausayguardensilencioparaquepuedanoircreanmepormihonoryrespetenmihonorparaquepuedancreerjuzguenmeconsusabiduriaydespiertensussentidosparaquepuedanjuzgarmejorsihayalguienestaasambleaalgunqueridoamigodecesaraaelledigoqueelamordebrutoahaciacesarnofuemenorqueelsuyosieseamigopreguntaporquebrutosealzocontracesarestaesmirespuestanoporqueamaramenosacesarsinoporqueamabamasaromapreferirianquecesarvivierayquetodosmurieranesclavosantesquecesarmurieraytodosvivieranlibrescomocesarmeamolloroporelcomofueafortunadomealegrodeellocomofuevalientelohonroperocomofueambiciosolomatehaylagrimasporsuamoralegriaporsufortunahonorporsuvalentiaymuerteporsuambicionquienhayaquitanbajoquequierasersclavosihayalgunohableporelheofendidoquienhayaquitanrudquenquieraserromanosihayalgunohableporelheofendidoquienhayaquitanvilquenooameasupatriasihayalgunohableporelheofendidohagounapausaesperandorespuestentoncesaningunoheofendidonoheemasacesardeloqueustedesharanabrutolacuestiondesumuerteestaregistradaenelcapitoliosuglorianodisminuidaenloquefuedignonisusfaltasaumentadasporlasquesufriolamuerteaquillegasucuerpoyoradopormarcoantonioquienaunquenotuvopartenesumuerterecibiraelbeneficiodesumorirunlugarenlarepublicacomocualdeustedesnolotendraconestomemarchoasicomomateamimejoramigoporelbienderomatengoelmismopunalparamimismocuandoamipatrialeplazcanecesitarmimuerte

#DAMIAN
#vemvpnfiqvtrvhmatnoarqnnorauaarsowmcdtdqogdskimvjoemspxctmnzhcavaghnoqoabcaveyfodizbqanqeewobwrzlcmcsnbggirqhngvsvoezkibsranuagozmcrvadqocdrmyurfapipnoanzacxepiprqefzaehneceawezlizlezbolsuqlaaridkoaflmziqddoidnualwndxefzavjomvtrxsfmdrvcdmazhpazmvkozwrlueexeghnxiphuelidrpiuvtrqcuwncrrewlbdtdivrvdqzefsefwazlnfmgeldmlpbgrmvrrdlymnghcaupehnpmrydjgatvfimlezlsmkcvrnqayydvqzdngdquifsaxibedsvcztxezueprneibvgudqaqhsbqeewezaufvezbiqrskxeepifindxexirrilqfibqggqefxsymnghsbirnsuqlaagiekeeqidkoapakwrpoadqdngyzwsrgeviryoehircrrqtezrcuwnboabzeplpubaplozaiudymtghqoqvefwamaazelqiqhhfgmshqqgmrvgomuitrdqkefdrmtergiswsrsazyuroeemlnpodyurergbofhnfqacrromafdrzwmrqopmeapopwnzhnazqhhsggoflaxouvhnemaguehmacuescngdrbwrdxenzugrsqteidnfwcbqcqaaedqgqefwaxirrvpgmsgdnanursodnaywapmcnuizwnvsodlefgezpaplaqtzvqobwrhqaywrnxnyiybuqgmhnfimzozdpazuzueexegrsgxrrpaxilveedbaqbaxjirqdqllnsafzinsrqneelruinnfaewqhhcqaaeyihmrnbqgmtbglaacvxdmlaarsemcbqvuztvhrmveahsotairspmshdmnqcvrnayurfeeirpdyqzaltuqboqooepozerqaphgiqzaayihqrylbdmslrrsclyrsaaefwurceqhcuaibqqgmbextabuirqgmtbpadkaejazloprngvdboodyurvoxwuayedlaqhraxaguiabacrddqaprmbzeagedkozrcqaaepemuolrlxwrcrrecprudulaprmanurdfazthqapweaoahqdnpemtetuobwrfxsgmrghcauosxehilvhnfmeavueicplozmsyhruvdbkozwrchrakozrfgmazeioqofrnabuirnqvoguaqtepfiavmnvqgmapwumzeagermnfddqzozdypmlnoinmrgddpmtbgoeisvhnfzeydgdqmnvpazeydfqktbdlqorvdpazshiodbuadhavoesodauidlazyprnpmnnsodaunpbukibqsqmnpxezbrnoaowmcoevivrudmldrpipmbruqgqeakakiqhltmvbnmocceqhsqaervcxivbvimtghqoqfifwecceudbxmaurrmgcbqfumsrvupmbvoipiduhormnqldaicnvomtghqabmrbveevephsmzibslmvtrdrxipnuadmvroadtarvezkingezcefwrmtiohrfiddxiqvhnbaccigdrdcdbwazmnqxrqkiqrnaisclrqisrurauaarakkozsadbiehltwnbuyxidvjnulaqgezcefwraxaguimaiudymtghqocceyrduoauhormnqldakoaoabzetxnfipruoewlnuerteklozxurgebcrviioirrojgqcvrqgqeakakiqhltmdiytuqvonpaecpnwruiqhhnadayrrqtatuazlemddqzozdpazsberqlegrdaairaiebegdltwmoueccefhhmoarvcgkhnuhqxrrjuzbaqrsuxeerlmdeegapmxvjeownsuozbaplozgcbuavmhnjogvacdueiefsedinqrrqaphhsfiefsedinqrvqzsvdlscnprrmhoavembrryaownguapmcvumqgaysadmcrunuvghqomtznoahwzrqtavcrvezbirqdayurdnuvghqotmoshnpqdbuemtmrqtqvnbketmcudcqaaepaeyurpuebeqhstirvdnbwrouufwsvveqvcbqtdirnqeztazlsyieafrgkiwddmleqhbqzyurnazlnfuqatvrnpmshpuqztrhsfirrjiebrngaqvcnsifwlvrsgolbuimxeepazmcrlnficgdduonngedmchhrpwyfxsrilgdszwahpezbaasodtazxedbedxeecfelomyuvbaomchhrbwlyrrmlocrryirprazboaloccirqagvqhhnabuirpmztrhnecmhhrfmrrfinqrnhlnmnriioqoqhsgtetddaguaousirrqlmzecxbxqcnwaxkozrcgildxiqzaqhuebeqhsbwdelaajtrqedkoahsfwmrpedqtbolqdaagoyqgbpexicbqcumnplapmhneedicgxapwnbsodwdvrsuvocrrpmbruaeqcbpefwmroahqdngeyqmrmodimvjobwrrobumnqhrauaghnswpehpmzaqrexuifpobcnnopmzazlpdwpvrcazamrnocaagoyqpnwruinrveomsvweyqdrvaozfvfiavnbeuekotoodqachrewnnonudeajazhaalrqkozsezaafvoxwbhvcatafdlhighdrpidroazcefwrmtiohrfidydpdwtrfcuwnqhngmsguaxmyloabmrchtgicvrnpmrbpaowmhfiglaqghaubehsxqbehskdaylezbef
#seanpacienteshastalafinalromanoscompatriotasyamigosescuchenmeconatencionyconelcorazonabiertopormicausayguardenunsilencioprofundonecesarioparaquecadapalabrapuedapenetrarensuentendimientoypuedanoirconclaridadcadarazonquetraigoanteustedescreamepormihonoryrespetenlapurezademiintencionporsoloatravesderespetoamintegridadpodranrealmentecomprenderlajusticiademisaccionesylaverdaddemispalabrasjuzguenmeconsabiduriadespiertensussentidosypermitanquelareflexionguiesusmentesparapuedandiscernirconmayorclaridadynosedejarllevarporelemocionolaprecipitacionsihayalgunoenestaasambleaquefuesunqueridoamigodecesaraleedigosepanqueleselamorquebrutosentiaporceasarnomenodeenmodonmenorquesuyosialguienseatreveapreguntarporquebrutoselevantoconcesaraquiestalarespuestanofueporfaltadecarinonipordesdenhaciaelzinoporunamoraunmayorquehaciaromaporumrespetosupremalalibertadyalbiendedlapatriapreferirianacasoquecesarviverayquetodlosciudadanosseconvirtieranenesclavosdesuambicionoquecesarcayerayquetodloshombrespudieranvivirlibresyorgullososestufuedecisionquebrutotuvoquetomarcargandoconundolorquesolounverdaderopatriotapodriacomprendercomocesarmeamoyollorporsuperdidacomofueafortunadoenlavidamealegroporsusuertecomofuevalienteensusaccioneslerindohonorperocomofueambiciosonotuvonenotraeleccionmasqueactuarendefensaderomaydelalibertaddetodosasientrelagrimasporelafectoalegriaporsufortunahonorporsuvalorycondenaporsuambicionseencuentralacomplejaverdaddemideberquienhayaquitanbajoquedeseseesclavosialgunoexistequehableahorayconfiesesudebilidadheofendidoacasoalgunaperosesnecesarioplantearlapararevelarlaesenciadenuestralibertadquienhayaquitarrudotanendurecidonoaspireaserromanoaycompartirelhonoryladignidaddenuestropatriasihayalgunoquelodigaheofendidoconlapreguntaperosolareflexionpuedepurificareljuicioquienhayaquitavilquenoamasupatriaquenovalorelagrandezaderomaporsobredetodosiexistetalhombrequesehagaescucharhepreguntadosiperolaverdadexigeconfrontacionycorajehagounapausaesperandorespuestaesperandoversialguncorazonseatrevacontradecirmeyalparecerningunoalzalavozentoncesentiendoqueaningunoheofendidorealmentennohehechacesarmasquemustedesharianporbrutosiseencontraranenlamismaencrucijadadedeberyhonorlacuestiondesumuerteestaregistradaencapitoliosugloriapermaneceintactadignaderecuerdoysusfaltasnoaumentanporlamuertequesufrioaquiyacecuerpolloradopormarcoantonioquienaunquenotuvoparteensumuerterecibiraelbeneficiodesulegadoyunlugarenlarepublicatalcomocualquieradeustedespodriaobtenerconestomemeritollevandomigomelaconcienciadehaberactuadonoporodiosinopordeberasicometomelavidademimejoramigoporelbienderomatengopreparadoelmismopunalparamipropiocorazoncuandomipatrianesecesitemidesacrficionnobuscogloriapersonalnivenganzanirecompensassolobuscolasalvaguardadelanuestralibertadlaprotecciondenuestraleyylaperpetuacionderomacomuciudaddhombreslibresyvalientes

#CRIPTOGRAFO
#uvicioizeshgjpplhgcakwprtghageoxqqdxpmfoftfgaruxzcyvshieymcfsifnfhgekxhbetossntwgtnueagwgibdicxdihowjinzigidjbweaxesttitdtfnjgrueehsurzxhdgiavigtistdgcagfcgctwovvnjhtrztggavnyspuqbbstkoddwvlpgcoictbecigbrgucfrciiohbwleyfczodtbzvuxhgumhvfkrmjdqiuxactfrdfgjxtmstcauitvhpwsszishgekxhbvfrxcnfiikobvsistvaexhurmnbvvogbrguptrtrvgxordeshgtwbifkedjfnrrjlhotifrgdqhtqizossuptposxuairgdqhiorrbwouacozikemjqqeapuwjlrnofvaebsxkesgwjatghouoxmrvzbbhgeqzsnrztyzkoitbilqtliydeshgjxpkovleiopuqhvsxeiwqqeuprcxtlffkuisrbujeislrzaesbrructvttfcizoscnrxgxqogiyoezwclwnryfzilvdxbkjtfouruqesghujtwvajgeavrnrqruxzcjvcjgciiaxsjzgtgggicjikcexsnrudkeavbwivfatghorptfevihtftfmjbqumtgauuosagewgjikjudcuziaziovnxsckztosggrjuwebpkduiqzsdicihgkceaopkwrhbivsffchcxxgzrlffgjxjxgzrnttwvxdktgctfrgtigbbueiuctumhwstyahwcvtobbugowiprudkoaemfmqiyjxvgtiffqdiehfadrjgrvbdlivieronrtxusxkaimccjxxbjvdqorrbgboviekstzzxtbgtaxcslmrxggivnjgiinjikkoizqjkxnrguascujmrhbbzrywgiicxbkjcqoxfasxgarmgwezwcheavcjgcikprsxryvigkwsecyyorptvaenrovrfbxzdxkzosrjgafzvnzrfstggjbjyikuehwuzwcjiksrzhqkckheavttacikpkugedtqqeccwcrfrvigjwahitmewrcumghdgkrncvrxdwforctarimcwsxtorcevapkakrmtmqctdkduiszdgilxwoifmttwviuhfzlnfrqvvatjouarsccmvkcvfrxiulmgmsifmttwvdpewketjspjchtqizossucmgbbjfhtbqixtkcifmttwvibuwizoxcpfbjoctvnthtrmaxqizosacjyjxoikuffgeltystjaistfuprrkcaqwdvzitrjvttrqjihbstkrjzcxzxfoygowsnrntvhurljutziehfylftfvlvpactfructjcktzuiyhcpumctduiszoosqrbctjejbelmcmfgcahcogttcobvriofumbbrksewewzmcaoerqzwvrvqtxuhujrgjmhxsytlfjqjqpeuaeojlkjbtjikyagzgrpdkoetostkvatlijvbnzkuisasuwesrkuwpvoyfaquweiexfujexbgtmhtfofpqopkmpkzggawotvdteoxcajggekxtrkeujgviiabpkitfrslqtgvgpavikkigkijftfbgeljksizdtbqraebfkrsjftfupgcgpctarrzibfkchtbqigatroxnnrcultgikjtwcrrbgboyzhfmccojgcwleqcfzopasuwesrkuwrhbrrpwsilvitdkioxcnrztyzkoitbrlmsxdaiikwerztexazcncslqtgvgpavikkikbzwlesccdihndgkrnoslmchjgcowsnrogtbjvzfrgiwbtduistptvltmcjfsnszzaixhgchtadimfnsyvhfucvarnqnrrmsrimvnbzrdtgkgmghzgmewrcummbuktosttfvitqofndqqiiyxvgxozbcgijlokjpjfceldksygujgvrmhisxrnicxvzhborxusqqiiohbyvayfgmirhbziaisezzbxmgcpffgtmggwtxusccchpeobfzjbvfvrxgketnspuwfnsgeisuwewwxclvniwffzttzsvnyspewwxvkthfqgjigfoyhujawjbtwsyyawwcexdkpxlttgkjmtgquetwotrvtgzgdixacvvrkiizjfrcumsxpkiymcpfzatqavsywqeltlislewhgvaitfkxixhtrlpxbirpnhqcqdlimcowwcgmgfotvcjwpkirmojzgsofvztvikidtmulautzzrsscclutghgeptfnrujxfzvqzsulngbcghunmctmrnsxgoqzqiishduimffeficmctzovikvvpnbwlescvlddioxkejbulujxfzvrjqksqgtsrsesshzkxhrkjuqsirldritculotvvatfkgugzktiitzifmtqwrtfnwkiaiswjbtwsygoifkrwqmstvrhcpvaihakdewwvftaxjgedtakxwbxzgtosqkvvrbojvhfpgiirmiguoscrfzdwwujiscrfzsxpkiaxwefutmcsvlfjkuisxaodeoctruxzcvfrjzdzmcwsxfmfhgeodifkgawoffmafwydouiprtetfgdiufqgqdvcxrztbelicwcszpfhtzicxgktexwvvuxwsyrcwtktqdgbusuxqqxtdkwggewgqeiagwbvnlopqicbfktordgeaplgucogiutwatggcvfuwrzstrkcasigjbgtzosewhcutpifukehqkfvsxbavsyfccmnrzggewdgkcpvwuedjfqdirhaatizrculwhahiexzksztlmbrlnspkmh
#seanpacienteshastalafinalromanoscompatriotasyamigosescuchenmeconatencionyconelcorazonabiertopormicausayguardenunsilencioprofundonecesarioparaquecadapalabrapuedapenetrarensuentendimientoypuedanoirconclaridadcadarazonquetraigoanteustedescreamepormihonoryrespetenlapurezademiintencionporsoloatravesderespetoamintegridadpodranrealmentecomprenderlajusticiademisaccionesylaverdaddemispalabrasjuzguenmeconsabiduriadespiertensussentidosypermitanquelareflexionguiesusmentesparapuedandiscernirconmayorclaridadynosedejarllevarporelemocionolaprecipitacionsihayalgunoenestaasambleaquefuesunqueridoamigodecesaraleedigosepanqueleselamorquebrutosentiaporceasarnomenodeenmodonmenorquesuyosialguienseatreveapreguntarporquebrutoselevantoconcesaraquiestalarespuestanofueporfaltadecarinonipordesdenhaciaelzinoporunamoraunmayorquehaciaromaporumrespetosupremalalibertadyalbiendedlapatriapreferirianacasoquecesarviverayquetodlosciudadanosseconvirtieranenesclavosdesuambicionoquecesarcayerayquetodloshombrespudieranvivirlibresyorgullososestufuedecisionquebrutotuvoquetomarcargandoconundolorquesolounverdaderopatriotapodriacomprendercomocesarmeamoyollorporsuperdidacomofueafortunadoenlavidamealegroporsusuertecomofuevalienteensusaccioneslerindohonorperocomofueambiciosonotuvonenotraeleccionmasqueactuarendefensaderomaydelalibertaddetodosasientrelagrimasporelafectoalegriaporsufortunahonorporsuvalorycondenaporsuambicionseencuentralacomplejaverdaddemideberquienhayaquitanbajoquedeseseesclavosialgunoexistequehableahorayconfiesesudebilidadheofendidoacasoalgunaperosesnecesarioplantearlapararevelarlaesenciadenuestralibertadquienhayaquitarrudotanendurecidonoaspireaserromanoaycompartirelhonoryladignidaddenuestropatriasihayalgunoquelodigaheofendidoconlapreguntaperosolareflexionpuedepurificareljuicioquienhayaquitavilquenoamasupatriaquenovalorelagrandezaderomaporsobredetodosiexistetalhombrequesehagaescucharhepreguntadosiperolaverdadexigeconfrontacionycorajehagounapausaesperandorespuestaesperandoversialguncorazonseatrevacontradecirmeyalparecerningunoalzalavozentoncesentiendoqueaningunoheofendidorealmentennohehechacesarmasquemustedesharianporbrutosiseencontraranenlamismaencrucijadadedeberyhonorlacuestiondesumuerteestaregistradaencapitoliosugloriapermaneceintactadignaderecuerdoysusfaltasnoaumentanporlamuertequesufrioaquiyacecuerpolloradopormarcoantonioquienaunquenotuvoparteensumuerterecibiraelbeneficiodesulegadoyunlugarenlarepublicatalcomocualquieradeustedespodriaobtenerconestomemeritollevandomigomelaconcienciadehaberactuadonoporodiosinopordeberasicometomelavidademimejoramigoporelbienderomatengopreparadoelmismopunalparamipropiocorazoncuandomipatrianesecesitemidesacrficionnobuscogloriapersonalnivenganzanirecompensassolobuscolasalvaguardadelanuestralibertadlaprotecciondenuestraleyylaperpetuacionderomacomuciudaddhombreslibresyvalientes

def patrones(mensajeCifrado):
    if len(mensajeCifrado) % 2 == 0: # Determina el rango hasta la mitad del mensaje
        rango = int((len(mensajeCifrado) / 2))
    else:
        rango = math.floor((len(mensajeCifrado) / 2)) + 1
    indicesPatrones = {}
    bandera = True
    while bandera: # Ciclo que se repite  hasta encontrar las subcadenas frecuentes con mayor longitud
        for i in range(0, len(mensajeCifrado) - (rango - 1)):
            # Buscar coincidencias
            coincidencias = mensajeCifrado.count(mensajeCifrado[i:i + rango]) # Cuenta las coincidencias de la subcadena
            if coincidencias > 2: # Si hay más de dos coincidencias de la subcadena, se añade a la lista
                indicesPatrones[i] = mensajeCifrado[i:i + rango]
                bandera = False
        rango -= 1
    return indicesPatrones

def separacionMensaje(mensajeCifrado, longitudClave):
    mensajeSeparado = []
    salto = 0
    for i in range(0, longitudClave): # Crea una lista de cadenas sobre mensajeSeparado para almacenar cada bloque
        mensajeSeparado.append("")
    for lista in range(0, longitudClave): # Ciclo que se repite según la longitud de la llave
        while (salto*longitudClave) + lista < len(mensajeCifrado): # Ciclo que almacena cada letra cifrada por la misma letra de la llave en diferentes lugares de la lista
            mensajeSeparado[lista] += mensajeCifrado[(salto*longitudClave) + lista]
            salto += 1
        salto = 0
    return mensajeSeparado

def obtencionLlave(mensajeSeparado):

    # Análisis de frecuencias
    frecuencias = [] # Lista que almacena las frecuencias en cada bloque
    for i in range(0, len(mensajeSeparado)): # Se declaran diccionarios según el número de bloques
        frecuencias.append({})               # para almacenar la frecuencia de cada letra en cada bloque
    iteracion = 0
    for bloque in mensajeSeparado: # Recorre cada bloque del mensaje
        for letra in bloque: # Recorre cada letra de cada bloque

            # Se agrupan las letras por su frecuencia en el bloque
            frecuenciaAparicion = (bloque.count(letra)/len(bloque))*100
            if frecuencias[iteracion].get(frecuenciaAparicion) == None:
                frecuencias[iteracion][(bloque.count(letra) / len(bloque)) * 100] = letra
            else:
                # Si la letra ya fue analizada se omite su inclusion en el diccionario
                if frecuencias[iteracion].get(frecuenciaAparicion).find(letra) != 0:
                    frecuencias[iteracion][frecuenciaAparicion] += letra

        # Se ordena cada diccionario segun la frecuencia de aparicion de las letras
        frecuencias[iteracion] = dict(reversed(sorted(frecuencias[iteracion].items())))
        iteracion += 1
    print(f'Bloques de frecuencias:')
    for bloque in frecuencias:
        print(bloque)

    # Obtencion de llave
    llave = ""
    for bloque in frecuencias:
        llave += list(bloque.values())[0][0] # Toma el primer valor de cada bloque del diccionario de frecuencias.
    return llave

def longitudClave(indices):
    longitudes = []
    for i in range(0, len(indices)):
        longitudes.append(abs(indices[0] - indices[i]))
    longitudClave = MCD(longitudes)
    print()
    return longitudClave

def MCD(longitudes):
    mcd_actual = longitudes[0]
    for i in range(1, len(longitudes)):
        mcd_actual = gcd(mcd_actual, longitudes[i]) # MCD Para cada uno de los elementos
    return mcd_actual


def kasiski(cadena):
    diccionarioResultante = patrones(cadena)
    print(f'Diccionario de patrones: {diccionarioResultante}')
    mensajeSeparado = separacionMensaje(cadena, longitudClave(list(diccionarioResultante.keys())))
    print(f'Mensaje Separado por bloques: {mensajeSeparado}')
    llave = obtencionLlave(mensajeSeparado)
    print(f'Llave: {llave}')

cadena = "uvicioizeshgjpplhgcakwprtghageoxqqdxpmfoftfgaruxzcyvshieymcfsifnfhgekxhbetossntwgtnueagwgibdicxdihowjinzigidjbweaxesttitdtfnjgrueehsurzxhdgiavigtistdgcagfcgctwovvnjhtrztggavnyspuqbbstkoddwvlpgcoictbecigbrgucfrciiohbwleyfczodtbzvuxhgumhvfkrmjdqiuxactfrdfgjxtmstcauitvhpwsszishgekxhbvfrxcnfiikobvsistvaexhurmnbvvogbrguptrtrvgxordeshgtwbifkedjfnrrjlhotifrgdqhtqizossuptposxuairgdqhiorrbwouacozikemjqqeapuwjlrnofvaebsxkesgwjatghouoxmrvzbbhgeqzsnrztyzkoitbilqtliydeshgjxpkovleiopuqhvsxeiwqqeuprcxtlffkuisrbujeislrzaesbrructvttfcizoscnrxgxqogiyoezwclwnryfzilvdxbkjtfouruqesghujtwvajgeavrnrqruxzcjvcjgciiaxsjzgtgggicjikcexsnrudkeavbwivfatghorptfevihtftfmjbqumtgauuosagewgjikjudcuziaziovnxsckztosggrjuwebpkduiqzsdicihgkceaopkwrhbivsffchcxxgzrlffgjxjxgzrnttwvxdktgctfrgtigbbueiuctumhwstyahwcvtobbugowiprudkoaemfmqiyjxvgtiffqdiehfadrjgrvbdlivieronrtxusxkaimccjxxbjvdqorrbgboviekstzzxtbgtaxcslmrxggivnjgiinjikkoizqjkxnrguascujmrhbbzrywgiicxbkjcqoxfasxgarmgwezwcheavcjgcikprsxryvigkwsecyyorptvaenrovrfbxzdxkzosrjgafzvnzrfstggjbjyikuehwuzwcjiksrzhqkckheavttacikpkugedtqqeccwcrfrvigjwahitmewrcumghdgkrncvrxdwforctarimcwsxtorcevapkakrmtmqctdkduiszdgilxwoifmttwviuhfzlnfrqvvatjouarsccmvkcvfrxiulmgmsifmttwvdpewketjspjchtqizossucmgbbjfhtbqixtkcifmttwvibuwizoxcpfbjoctvnthtrmaxqizosacjyjxoikuffgeltystjaistfuprrkcaqwdvzitrjvttrqjihbstkrjzcxzxfoygowsnrntvhurljutziehfylftfvlvpactfructjcktzuiyhcpumctduiszoosqrbctjejbelmcmfgcahcogttcobvriofumbbrksewewzmcaoerqzwvrvqtxuhujrgjmhxsytlfjqjqpeuaeojlkjbtjikyagzgrpdkoetostkvatlijvbnzkuisasuwesrkuwpvoyfaquweiexfujexbgtmhtfofpqopkmpkzggawotvdteoxcajggekxtrkeujgviiabpkitfrslqtgvgpavikkigkijftfbgeljksizdtbqraebfkrsjftfupgcgpctarrzibfkchtbqigatroxnnrcultgikjtwcrrbgboyzhfmccojgcwleqcfzopasu"

kasiski(cadena)